In [1]:
import pandas as pd
f = pd.read_csv("/Users/kbhaskar/Desktop/ALL-DESKTOP-ITEMS-2022/supercomputing/dataaa.csv")

In [80]:
n = pd.read_csv("/Users/kbhaskar/Desktop/ALL-DESKTOP-ITEMS-2022/supercomputing/sampleData2.csv")
theList = list(n['Disease state'])

In [3]:
f = f.iloc[1: , :]
f.head()

ID_REF  GSM4299202  GSM4299203  GSM4299204  GSM4299205  GSM4299206  \
1  cg00000029    0.610080    0.461774    0.532801    0.525638    0.565315   
2  cg00000108    0.892013    0.874571    0.864435    0.888415    0.876623   
3  cg00000109    0.679462    0.743489    0.750426    0.766076    0.719490   
4  cg00000165    0.380888    0.315226    0.408930    0.363258    0.355817   
5  cg00000236    0.746092    0.692648    0.703013    0.729159    0.727424   

   GSM4299207  GSM4299208  GSM4299209  GSM4299210  ...  GSM4299655  \
1    0.552355    0.527146    0.547243    0.372868  ...    0.484418   
2    0.877342    0.890696    0.889398    0.904566  ...    0.882659   
3    0.701337    0.732295    0.732074    0.785893  ...    0.753637   
4    0.366407    0.391705    0.324435    0.341246  ...    0.358236   
5    0.699636    0.705997    0.733631    0.758436  ...    0.711934   

   GSM4299656  GSM4299657  GSM4299658  GSM4299659  GSM4299660  GSM4299661  \
1    0.617885    0.561003    0.496887    0.580232    0.535366    0.498475   
2    0.885742    0.886964    0.864362    0.876606    0.901069    0.887756   
3    0.723688    0.779231    0.755308    0.716716    0.775408    0.741219   
4    0.382305    0.463078    0.394118    0.445603    0.361730    0.385927   
5    0.691133    0.679940    0.677763    0.663610    0.690712    0.728422   

   GSM4299662  GSM4299663  GSM4299664  
1    0.540064    0.550954    0.530547  
2    0.874309    0.883725    0.877415  
3    0.696181    0.705243    0.701283  
4    0.387760    0.354690    0.419075  
5    0.735839    0.630362    0.735451  

[5 rows x 301 columns]

In [4]:
f = f.transpose()

In [5]:
f.columns = f.iloc[0] 
f = f[1:]
f.head()

ID_REF     cg00000029 cg00000108 cg00000109 cg00000165 cg00000236 cg00000289  \
GSM4299202    0.61008   0.892013   0.679462   0.380888   0.746092   0.589528   
GSM4299203   0.461774   0.874571   0.743489   0.315226   0.692648   0.557148   
GSM4299204   0.532801   0.864435   0.750426    0.40893   0.703013   0.502304   
GSM4299205   0.525638   0.888415   0.766076   0.363258   0.729159   0.570564   
GSM4299206   0.565315   0.876623    0.71949   0.355817   0.727424   0.562674   

ID_REF     cg00000321 cg00000363 cg00000622 cg00000658  ... ch.X.92435715F  \
GSM4299202   0.466989   0.400957   0.078471   0.784323  ...       0.161222   
GSM4299203   0.351919    0.45058   0.077674   0.773451  ...       0.188354   
GSM4299204   0.443538    0.44472   0.071294   0.788483  ...       0.131077   
GSM4299205   0.309935   0.491466    0.07791    0.79236  ...       0.177268   
GSM4299206   0.394112   0.526306   0.071569   0.802383  ...        0.14255   

ID_REF     ch.X.92448175R ch.X.92543860F ch.X.92554290F ch.X.938089F  \
GSM4299202       0.250849       0.104451       0.089215     0.113149   
GSM4299203       0.319998       0.118353       0.112339     0.146336   
GSM4299204       0.230516       0.089132       0.100164     0.121263   
GSM4299205       0.266929       0.135109       0.114255     0.135639   
GSM4299206       0.214554       0.092172       0.098297      0.11272   

ID_REF     ch.X.94051109R ch.X.97129969R ch.X.97651759F ch.X.98007042R  \
GSM4299202       0.089409        0.19375       0.080471       0.179957   
GSM4299203       0.127122       0.231571       0.092285       0.236591   
GSM4299204       0.097196       0.220558        0.10204       0.189094   
GSM4299205        0.13163       0.258989       0.109607       0.230713   
GSM4299206        0.09393       0.220815       0.075832       0.195175   

ID_REF     !series_matrix_table_end  
GSM4299202                      NaN  
GSM4299203                      NaN  
GSM4299204                      NaN  
GSM4299205                      NaN  
GSM4299206                      NaN  

[5 rows x 410943 columns]

In [6]:
f.insert(0, "state", theList, True)

In [7]:
f.head()

ID_REF                          state cg00000029 cg00000108 cg00000109  \
GSM4299202  mild cognitive impairment    0.61008   0.892013   0.679462   
GSM4299203        Alzheimer's disease   0.461774   0.874571   0.743489   
GSM4299204        Alzheimer's disease   0.532801   0.864435   0.750426   
GSM4299205                    control   0.525638   0.888415   0.766076   
GSM4299206  mild cognitive impairment   0.565315   0.876623    0.71949   

ID_REF     cg00000165 cg00000236 cg00000289 cg00000321 cg00000363 cg00000622  \
GSM4299202   0.380888   0.746092   0.589528   0.466989   0.400957   0.078471   
GSM4299203   0.315226   0.692648   0.557148   0.351919    0.45058   0.077674   
GSM4299204    0.40893   0.703013   0.502304   0.443538    0.44472   0.071294   
GSM4299205   0.363258   0.729159   0.570564   0.309935   0.491466    0.07791   
GSM4299206   0.355817   0.727424   0.562674   0.394112   0.526306   0.071569   

ID_REF      ... ch.X.92435715F ch.X.92448175R ch.X.92543860F ch.X.92554290F  \
GSM4299202  ...       0.161222       0.250849       0.104451       0.089215   
GSM4299203  ...       0.188354       0.319998       0.118353       0.112339   
GSM4299204  ...       0.131077       0.230516       0.089132       0.100164   
GSM4299205  ...       0.177268       0.266929       0.135109       0.114255   
GSM4299206  ...        0.14255       0.214554       0.092172       0.098297   

ID_REF     ch.X.938089F ch.X.94051109R ch.X.97129969R ch.X.97651759F  \
GSM4299202     0.113149       0.089409        0.19375       0.080471   
GSM4299203     0.146336       0.127122       0.231571       0.092285   
GSM4299204     0.121263       0.097196       0.220558        0.10204   
GSM4299205     0.135639        0.13163       0.258989       0.109607   
GSM4299206      0.11272        0.09393       0.220815       0.075832   

ID_REF     ch.X.98007042R !series_matrix_table_end  
GSM4299202       0.179957                      NaN  
GSM4299203       0.236591                      NaN  
GSM4299204       0.189094                      NaN  
GSM4299205       0.230713                      NaN  
GSM4299206       0.195175                      NaN  

[5 rows x 410944 columns]

In [8]:
f['state'].replace(['control', 'mild cognitive impairment', "Alzheimer's disease"],
                        [0, 2,1], inplace=True)

In [9]:
for index, row in f.iterrows():
    if row['state'] == 2:
        f.drop(index,axis=0,inplace=True)


In [10]:
final = f.copy(deep = True)


In [11]:
final = final.iloc[: , :-1]

In [12]:
final.head(20)

ID_REF      state cg00000029 cg00000108 cg00000109 cg00000165 cg00000236  \
GSM4299203      1   0.461774   0.874571   0.743489   0.315226   0.692648   
GSM4299204      1   0.532801   0.864435   0.750426    0.40893   0.703013   
GSM4299205      0   0.525638   0.888415   0.766076   0.363258   0.729159   
GSM4299208      1   0.527146   0.890696   0.732295   0.391705   0.705997   
GSM4299209      0   0.547243   0.889398   0.732074   0.324435   0.733631   
GSM4299210      0   0.372868   0.904566   0.785893   0.341246   0.758436   
GSM4299211      1   0.615915   0.859725   0.697565    0.35587   0.716815   
GSM4299212      1   0.560133   0.880498    0.67459   0.344219   0.709805   
GSM4299213      0   0.585631    0.85399   0.668885    0.42835   0.727414   
GSM4299215      0   0.576306   0.881954    0.69193    0.33653   0.723318   
GSM4299219      0   0.519913   0.896802   0.733264   0.433911   0.679416   
GSM4299220      1   0.538819   0.866413   0.753524   0.395248   0.746736   
GSM4299221      1   0.594257   0.875678    0.66504   0.355678   0.611215   
GSM4299222      1    0.48337   0.909233   0.776657   0.392779   0.739362   
GSM4299223      1   0.482261   0.880446   0.708729   0.379399   0.813063   
GSM4299224      0   0.471882    0.88114   0.711556   0.355433   0.701151   
GSM4299225      1   0.518283    0.89488   0.775135   0.328553   0.768829   
GSM4299227      1   0.539084   0.877638   0.773697   0.413944   0.689144   
GSM4299228      1   0.539329    0.85672   0.744106   0.354451   0.723059   
GSM4299230      1   0.494715   0.871979   0.762971   0.327607   0.733726   

ID_REF     cg00000289 cg00000321 cg00000363 cg00000622  ... ch.X.881064F  \
GSM4299203   0.557148   0.351919    0.45058   0.077674  ...     0.221496   
GSM4299204   0.502304   0.443538    0.44472   0.071294  ...     0.150388   
GSM4299205   0.570564   0.309935   0.491466    0.07791  ...     0.226791   
GSM4299208   0.529936   0.291544   0.540371   0.077586  ...      0.19012   
GSM4299209   0.546514   0.357975   0.404772   0.077679  ...     0.160216   
GSM4299210   0.555781    0.55899   0.319499   0.068738  ...     0.126779   
GSM4299211   0.502097   0.417428   0.462604   0.080491  ...     0.139766   
GSM4299212    0.52316   0.307098   0.435887   0.064938  ...     0.218076   
GSM4299213   0.510831   0.356643   0.446342   0.084937  ...     0.256767   
GSM4299215    0.57232    0.40239   0.409956   0.081604  ...     0.239967   
GSM4299219   0.567633   0.385663   0.421231   0.081326  ...     0.241527   
GSM4299220   0.521845    0.42793   0.462638   0.080626  ...     0.212745   
GSM4299221   0.480744   0.387718   0.432973   0.078618  ...      0.21747   
GSM4299222   0.578432   0.375796     0.4256   0.072822  ...     0.189054   
GSM4299223   0.582515   0.415743   0.375911   0.080528  ...     0.178095   
GSM4299224   0.555804   0.384688   0.387785   0.075669  ...     0.243339   
GSM4299225   0.590257   0.361467   0.454668   0.079183  ...     0.286259   
GSM4299227   0.449693    0.49617   0.347574   0.073667  ...     0.262351   
GSM4299228   0.555368   0.401037   0.415069   0.076584  ...     0.259275   
GSM4299230   0.571115   0.398447   0.343386   0.081745  ...     0.200378   

ID_REF     ch.X.92435715F ch.X.92448175R ch.X.92543860F ch.X.92554290F  \
GSM4299203       0.188354       0.319998       0.118353       0.112339   
GSM4299204       0.131077       0.230516       0.089132       0.100164   
GSM4299205       0.177268       0.266929       0.135109       0.114255   
GSM4299208       0.155201       0.197577        0.08889       0.103112   
GSM4299209       0.123312       0.209574       0.104055       0.089769   
GSM4299210       0.096218       0.221558       0.078691       0.121342   
GSM4299211       0.156822       0.229214       0.065123       0.072114   
GSM4299212       0.200599       0.259011        0.09405       0.072403   
GSM4299213       0.145368       0.288984       0.134658       0.097458   
GSM4299215       0.180303       0.232173       0.142274       0.10

In [13]:
#virtually no constant features 
X = final.copy()
y = X["state"]
X.drop(labels=['state'], axis=1, inplace = True)
from sklearn.feature_selection import VarianceThreshold
sel = VarianceThreshold(threshold=0)
sel.fit(X)
sum(sel.get_support())

410942

In [77]:
#information gain 
from sklearn.feature_selection import mutual_info_classif as MIC
from sklearn.feature_selection import SelectKBest
best = SelectKBest(MIC, k=2000)
X_kbest = best.fit_transform(X, y)
print(X_kbest)
cols = best.get_support(indices=True)
features_df_new = X.iloc[:,cols]

print('Original number of features:', X.shape)
print('Reduced number of features:', X_kbest.shape)

[[0.421873267 0.851228717 0.150309793 ... 0.1228647 0.127295 0.1184522]
 [0.3876552 0.833177781 0.138432278 ... 0.1115789 0.1521533 0.09212525]
 [0.386771178 0.84151842 0.162327323 ... 0.1178759 0.1845582 0.09706694]
 ...
 [0.440912486 0.837726732 0.145316002 ... 0.1364615 0.1753143 0.1087925]
 [0.398487094 0.859073709 0.158532818 ... 0.1640339 0.2353032 0.1253727]
 [0.400173076 0.83762648 0.145412646 ... 0.1493244 0.2069369 0.1307751]]
Original number of features: (189, 410942)
Reduced number of features: (189, 2000)


In [62]:
mi_score = MIC(X_kbest,y)
print(mi_score)

[0.19264773 0.17243542 0.17439579 0.16723334 0.16790445 0.16615951
 0.17311981 0.17650831 0.17988855 0.16598824]


In [78]:
features_df_new = X.iloc[:,cols]

features_df_new.head()

ID_REF     cg00015319 cg00025155 cg00026974 cg00028022 cg00031456 cg00039326  \
GSM4299203   0.421873   0.851229    0.15031   0.707828   0.098658   0.712111   
GSM4299204   0.387655   0.833178   0.138432   0.135718   0.096676   0.771445   
GSM4299205   0.386771   0.841518   0.162327   0.516837   0.088322     0.7206   
GSM4299208   0.393865   0.846298    0.14869   0.717963   0.086691   0.704739   
GSM4299209   0.358857   0.815052   0.136773   0.599327   0.102256   0.738764   

ID_REF     cg00047753 cg00052290 cg00055510 cg00061031  ... cg27660104  \
GSM4299203   0.829858   0.136022   0.879397   0.781921  ...   0.143466   
GSM4299204   0.809371   0.127969   0.852481    0.73344  ...   0.144573   
GSM4299205   0.853229   0.126165   0.884217   0.739058  ...    0.14422   
GSM4299208   0.775559   0.125029   0.856094   0.726822  ...   0.162629   
GSM4299209   0.795688    0.11658   0.862852   0.730198  ...    0.13865   

ID_REF     ch.11.2725754F ch.14.1824732F ch.2.4251330R ch.4.55637694R  \
GSM4299203       0.198981       0.158457      0.135177       0.150773   
GSM4299204       0.181497       0.134145      0.119429       0.151322   
GSM4299205       0.202654       0.164785      0.136001       0.157204   
GSM4299208       0.229071        0.15161      0.151102       0.135916   
GSM4299209       0.185059       0.113524      0.135937        0.12086   

ID_REF     ch.5.409282R ch.8.101580865F ch.8.120063967R ch.8.2343166R  \
GSM4299203     0.242285         0.11609        0.122865      0.127295   
GSM4299204     0.264831        0.117826        0.111579      0.152153   
GSM4299205     0.262381        0.115608        0.117876      0.184558   
GSM4299208     0.258086        0.119348        0.121227       0.15899   
GSM4299209     0.240571        0.122517        0.112891      0.162362   

ID_REF     ch.9.837340R  
GSM4299203     0.118452  
GSM4299204     0.092125  
GSM4299205     0.097067  
GSM4299208     0.101083  
GSM4299209     0.097632  

[5 rows x 2000 columns]

In [81]:
n['Disease state'].replace(['control', 'mild cognitive impairment', "Alzheimer's disease"],
                        [0, 2,1], inplace=True)
for index, row in n.iterrows():
    if row['Disease state'] == 2:
        n.drop(index,axis=0,inplace=True)
n.head()

Group   Accession                     Title  Source name       Tissue  \
1     -  GSM4299203  Genomic DNA from blood 2  whole blood  whole blood   
2     -  GSM4299204  Genomic DNA from blood 3  whole blood  whole blood   
3     -  GSM4299205  Genomic DNA from blood 4  whole blood  whole blood   
6     -  GSM4299208  Genomic DNA from blood 7  whole blood  whole blood   
7     -  GSM4299209  Genomic DNA from blood 8  whole blood  whole blood   

      Sex  Age  Disease state       Disease state2             Characteristics  
1    Male   86              1  Alzheimer's disease  age<65.exclusion: Included  
2  Female   80              1  Alzheimer's disease  age<65.exclusion: Included  
3    Male   81              0              control  age<65.exclusion: Included  
6  Female   76              1  Alzheimer's disease  age<65.exclusion: Included  
7  Female   69              0              control  age<65.exclusion: Included

In [82]:
list2 = list(n['Disease state'])
features_df_new.insert(0, "state", list2, True)

In [83]:
features_df_new

ID_REF      state cg00015319 cg00025155 cg00026974 cg00028022 cg00031456  \
GSM4299203      1   0.421873   0.851229    0.15031   0.707828   0.098658   
GSM4299204      1   0.387655   0.833178   0.138432   0.135718   0.096676   
GSM4299205      0   0.386771   0.841518   0.162327   0.516837   0.088322   
GSM4299208      1   0.393865   0.846298    0.14869   0.717963   0.086691   
GSM4299209      0   0.358857   0.815052   0.136773   0.599327   0.102256   
...           ...        ...        ...        ...        ...        ...   
GSM4299657      1   0.406016   0.847013   0.148621   0.517635    0.09543   
GSM4299661      0   0.401303   0.847812   0.127843   0.728677   0.095783   
GSM4299662      1   0.440912   0.837727   0.145316   0.647604   0.093899   
GSM4299663      1   0.398487   0.859074   0.158533    0.75365   0.099028   
GSM4299664      1   0.400173   0.837626   0.145413   0.514533   0.076803   

ID_REF     cg00039326 cg00047753 cg00052290 cg00055510  ... cg27660104  \
GSM4299203   0.712111   0.829858   0.136022   0.879397  ...   0.143466   
GSM4299204   0.771445   0.809371   0.127969   0.852481  ...   0.144573   
GSM4299205     0.7206   0.853229   0.126165   0.884217  ...    0.14422   
GSM4299208   0.704739   0.775559   0.125029   0.856094  ...   0.162629   
GSM4299209   0.738764   0.795688    0.11658   0.862852  ...    0.13865   
...               ...        ...        ...        ...  ...        ...   
GSM4299657   0.692657   0.793914   0.132681   0.874002  ...   0.163205   
GSM4299661   0.731533   0.807703   0.125936   0.868383  ...   0.152757   
GSM4299662    0.75387   0.796914   0.121482    0.84534  ...   0.150286   
GSM4299663    0.71569   0.743448   0.129285   0.864263  ...     0.1873   
GSM4299664   0.726932   0.762071   0.124031   0.858472  ...   0.186097   

ID_REF     ch.11.2725754F ch.14.1824732F ch.2.4251330R ch.4.55637694R  \
GSM4299203       0.198981       0.158457      0.135177       0.150773   
GSM4299204       0.181497       0.134145      0.119429       0.151322   
GSM4299205       0.202654       0.164785      0.136001       0.157204   
GSM4299208       0.229071        0.15161      0.151102       0.135916   
GSM4299209       0.185059       0.113524      0.135937        0.12086   
...                   ...            ...           ...            ...   
GSM4299657       0.233065       0.131675      0.144628        0.17828   
GSM4299661       0.197714       0.126104      0.135965       0.155736   
GSM4299662        0.21717       0.153018      0.130103       0.158181   
GSM4299663       0.224761       0.164301      0.147531       0.164976   
GSM4299664       0.215503       0.124486      0.181477       0.180285   

ID_REF     ch.5.409282R ch.8.101580865F ch.8.120063967R ch.8.2343166R  \
GSM4299203     0.242285         0.11609        0.122865      0.127295   
GSM4299204     0.264831        0.117826        0.111579      0.152153   
GSM4299205     0.262381        0.115608        0.117876      0.184558   
GSM4299208     0.258086        0.119348        0.121227       0.15899   
GSM4299209     0.240571        0.122517        0.112891      0.162362   
...                 ...             ...             ...           ...   
GSM4299657     0.313826        0.126415        0.124474      0.167036   
GSM4299661     0.300359        0.108417        0.117441      0.160201   
GSM4299662     0.286549        0.097984        0.136462      0.175314   
GSM4299663     0.348269         0.11373        0.164034      0.235303   
GSM4299664     0.353096        0.109975        0.149324      0.206937   

ID_REF     ch.9.837340R  
GSM4299203     0.118452  
GSM4299204     0.092125  
GSM4299205     0.097067  
GSM4299208     0.101083  
GSM4299209     0.097632  
...                 ...  
GSM4299657     0.138653  
GSM4299661     0.104891  
GSM4299662     0.108793  
GSM4299663     0.125373  
GSM4299664     0.130775  

[189 rows x 2001 columns]

In [30]:
features_df_new.to_csv("200DMRsfinal.csv")

In [33]:
import numpy as np
arr = np.array(mi_score)

In [49]:
mi_score_ind = np.where(arr > 0.18)[0]

In [50]:
print(len(mi_score_ind))

1


In [51]:
#this is the most strongly associated with ad
print(X.columns[mi_score_ind])

Index(['cg00131081'], dtype='object', name='ID_REF')


In [54]:
#make it less restrictive for pearson corr
mi_score_ind = np.where(arr > 0.07)[0]
print(len(mi_score_ind))

12571


In [55]:
print(mi_score_ind)

[    70    127    145 ... 410874 410876 410900]


In [56]:
new = pd.DataFrame()
for i in mi_score_ind:
    new.loc[:, X.columns[i]] = X.iloc[:, i]


    

In [57]:
new.insert(0,"state",y,allow_duplicates = True)
new.head()

state cg00003287 cg00006081 cg00007221 cg00008823 cg00013804  \
GSM4299203      1   0.221599   0.288777   0.799765   0.087764   0.818923   
GSM4299204      1   0.184068   0.338211   0.808965   0.087261    0.81809   
GSM4299205      0   0.215726   0.365243   0.820563   0.099197   0.827796   
GSM4299208      1   0.213043   0.419097    0.82618   0.079228   0.798267   
GSM4299209      0   0.239671     0.3571   0.811796   0.082803   0.791496   

           cg00014260 cg00014301 cg00015319 cg00015373  ... ch.8.101580865F  \
GSM4299203   0.767636   0.854562   0.421873   0.802597  ...         0.11609   
GSM4299204   0.753746   0.860253   0.387655   0.804395  ...        0.117826   
GSM4299205    0.75241   0.850197   0.386771   0.817958  ...        0.115608   
GSM4299208   0.733205   0.857015   0.393865   0.802185  ...        0.119348   
GSM4299209   0.777179   0.863184   0.358857   0.833081  ...        0.122517   

           ch.8.120063967R ch.8.128185533F ch.8.129857482F ch.8.2343166R  \
GSM4299203        0.122865        0.075468        0.098658      0.127295   
GSM4299204        0.111579        0.076786        0.094028      0.152153   
GSM4299205        0.117876          0.0842        0.082634      0.184558   
GSM4299208        0.121227        0.093524        0.096709       0.15899   
GSM4299209        0.112891        0.093103         0.08216      0.162362   

           ch.9.31239617R ch.9.77250961R ch.9.837340R ch.9.84078312F  \
GSM4299203       0.175132       0.134334     0.118452        0.09342   
GSM4299204       0.251391       0.117185     0.092125       0.095092   
GSM4299205       0.197029       0.109903     0.097067       0.099954   
GSM4299208       0.201531       0.127428     0.101083       0.099819   
GSM4299209       0.267603       0.110164     0.097632       0.096035   

           ch.X.115956070R  
GSM4299203         0.18074  
GSM4299204         0.11406  
GSM4299205        0.150427  
GSM4299208        0.115057  
GSM4299209        0.111816  

[5 rows x 12572 columns]

In [58]:
new.columns[0]

'state'

In [84]:
from pandas import *
import numpy as np
from scipy import stats
import itertools
correlations = {}
bestPos = []
bestNeg = []
alls = []
columns = new.columns.tolist()
#Find out which methylated regions are most correlated with ad using pearsonr correlation. For the machine learning model, the filters are less restrictive. 
for col_a, col_b in itertools.combinations(columns, 2):
    if col_a == 'state':
        r,p = stats.pointbiserialr(new.loc[:, col_a], new.loc[:, col_b])
        correlations[col_a + '__' + col_b] = stats.pointbiserialr(new.loc[:, col_a], new.loc[:, col_b])
        #differentiate between positively correlated with ad and negatively correlated - neg or pos pearsonr val
        if r > 0.25 and p < 0.05:
            bestPos.append(str(col_b))
            alls.append(str(col_b))
        elif r < -0.25 and p <0.05:
            bestNeg.append(str(col_b))
            alls.append(str(col_b))

result = DataFrame.from_dict(correlations, orient='index')
result.columns = ['PCC', 'p-value']
print(result.sort_index(ascending=False))

                             PCC   p-value
state__ch.X.115956070R  0.005270  0.942622
state__ch.9.84078312F  -0.029036  0.691651
state__ch.9.837340R     0.061370  0.401528
state__ch.9.77250961R  -0.086862  0.234642
state__ch.9.31239617R  -0.056035  0.443767
...                          ...       ...
state__cg00013804       0.129394  0.075975
state__cg00008823       0.012271  0.866910
state__cg00007221      -0.003022  0.967083
state__cg00006081       0.080906  0.268418
state__cg00003287       0.079568  0.276444

[12571 rows x 2 columns]


In [85]:
print(len(bestPos))
print(len(bestNeg))
print(bestPos)
print("")
print("")
print("")
print("")
print(bestNeg)

12
6
['cg00872580', 'cg01687878', 'cg02308560', 'cg03803541', 'cg05597748', 'cg07039378', 'cg08041350', 'cg08362785', 'cg11234111', 'cg19809499', 'cg20093992', 'cg20471691']




['cg00931843', 'cg02625024', 'cg09787089', 'cg10837111', 'cg17280129', 'cg21915970']


In [96]:
theNew = pd.DataFrame()
for (columnName, columnData) in new.iteritems():
    if columnName in alls:
        theNew[columnName] = columnData

In [125]:
theList = list(new['state'])
theNew.insert(0, "state", theList, True)

In [126]:
theNew.head()

state cg00872580 cg00931843 cg01687878 cg02308560 cg02625024  \
GSM4299203      1   0.741957   0.520322    0.66312   0.645766   0.647523   
GSM4299204      1    0.75267   0.450976   0.568184   0.662346   0.566585   
GSM4299205      0   0.764173   0.558849   0.564168   0.678242   0.598451   
GSM4299208      1   0.753863   0.502112   0.576756   0.638891   0.558299   
GSM4299209      0   0.704311   0.592388   0.552865    0.62293   0.613826   

           cg03803541 cg05597748 cg07039378 cg08041350 cg08362785 cg09787089  \
GSM4299203    0.61227   0.737019   0.666992   0.810235   0.689093   0.904685   
GSM4299204    0.58524   0.719758   0.685239   0.812503   0.652408   0.889046   
GSM4299205   0.658915   0.742304   0.655249   0.781928   0.647118   0.893107   
GSM4299208   0.502621   0.748831   0.662273   0.777186   0.671919   0.891049   
GSM4299209   0.558711   0.743302   0.662728    0.79993   0.598127   0.906523   

           cg10837111 cg11234111 cg17280129 cg19809499 cg20093992 cg20471691  \
GSM4299203   0.876497   0.117334   0.741231   0.130519   0.847848   0.662247   
GSM4299204   0.842047   0.112072   0.711015   0.129428   0.813189   0.634525   
GSM4299205   0.870295   0.112196   0.758712   0.137138   0.825668   0.670589   
GSM4299208   0.882926   0.118084   0.756137   0.107123   0.844765   0.596493   
GSM4299209   0.875213   0.108285   0.690659   0.099039   0.830341   0.654015   

           cg21915970  
GSM4299203   0.119378  
GSM4299204   0.138422  
GSM4299205   0.138922  
GSM4299208   0.129369  
GSM4299209   0.117032

In [127]:
theNew.to_csv("binaryBeLike.csv")

In [120]:
print(count)

0    96
1    93
Name: state, dtype: int64


In [109]:
print(len(n))

300


In [110]:
n = pd.read_csv("/Users/kbhaskar/Desktop/supercomputing/sampleData2.csv")

In [113]:
print(len(n))

300


In [69]:
dmr = pd.read_csv("/Users/kbhaskar/Desktop/ALL-DESKTOP-ITEMS-2022/supercomputing/DMRgenes.csv")
#dmr2 = pd.read_csv("/Users/kbhaskar/Desktop/supercomputing/DMRgenes.csv")
#dmr = dmr["ID"]
dmr

/Users/kbhaskar/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3166: DtypeWarning: Columns (11,14,15,36) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


ID        Name  AddressA_ID  \
0       cg00035864  cg00035864     31729416   
1       cg00050873  cg00050873     32735311   
2       cg00061679  cg00061679     28780415   
3       cg00063477  cg00063477     16712347   
4       cg00121626  cg00121626     19779393   
...            ...         ...          ...   
485572   rs7746156   rs7746156     33622366   
485573   rs1945975   rs1945975     23614475   
485574    rs966367    rs966367     16795360   
485575    rs877309    rs877309     54760445   
485576   rs4331560   rs4331560     10654345   

                                         AlleleA_ProbeSeq  AddressB_ID  \
0       AAAACACTAACAATCTTATCCACATAAACCCTTAAATTTATCTCAA...          NaN   
1       ACAAAAAAACAACACACAACTATAATAATTTTTAAAATAAATAAAC...   31717405.0   
2       AAAACATTAAAAAACTAATTCACTACTATTTAATTACTTTATTTTC...          NaN   
3       TATTCTTCCACACAAAATACTAAACRTATATTTACAAAAATACTTC...          NaN   
4       AAAACTAATAAAAATAACTTACAAACCAAATACTATACCCTACAAC...          NaN   
...                                                   ...          ...   
485572  TACCAACCAATACTCAAAATAACCCATACTAATCTTCCTATTCTTC...          NaN   
485573  CCACTTCTCTTTCCTCACCTACTTTCATTTAATTTAATACTTACCT...          NaN   
485574  ATAACTCCTTTAACTTTAAACACACATCTCTACACACAACCACATA...          NaN   
485575  CCCCAACCCAAAACCTCTATAATTCACAAAACACAAATTCACACTT...          NaN   
485576  CATAACATTTCTCATCCAATAACTCACTCCATCTTCCAATACTCCC...          NaN   

                                         AlleleB_ProbeSeq  \
0                                                     NaN   
1       ACGAAAAAACAACGCACAACTATAATAATTTTTAAAATAAATAAAC...   
2                                                     NaN   
3                                                     NaN   
4                                                     NaN   
...                                                   ...   
485572                                                NaN   
485573                                                NaN   
485574                                                NaN   
485575                                                NaN   
485576                                                NaN   

       Infinium_Design_Type Next_Base Color_Channel  \
0                        II       NaN           NaN   
1                         I         A           Red   
2                        II       NaN           NaN   
3                        II       NaN           NaN   
4                        II       NaN           NaN   
...                     ...       ...           ...   
485572                   II       NaN           NaN   
485573                   II       NaN           NaN   
485574                   II       NaN           NaN   
485575                   II       NaN           NaN   
485576                   II       NaN           NaN   

                                         Forward_Sequence  ...  DMR Enhancer  \
0       AATCCAAAGATGATGGAGGAGTGCCCGCTCATGATGTGAAGTACCT...  ...  NaN      NaN   
1       TATCTCTGTCTGGCGAGGAGGCAACGCACAACTGTGGTGGTTTTTG...  ...  NaN      NaN   
2       TCAACAAATGAGAGACATTGAAGAACTAATTCACTACTATTTGGTT...  ...  NaN      NaN   
3       CTCCTGTACTTGTTCATTAAATAATGATTCCTTGGATATACCAAGT...  ...  NaN      NaN   
4       AGGTGAATGAAGAGACTAATGGGAGTGGCTTGCAAGCCAGGTACTG...  ...  NaN      NaN   
...                                                   ...  ...  ...      ...   
485572                                                NaN  ...  NaN      NaN   
485573                                                NaN  ...  NaN      NaN   
485574                                                NaN  ...  NaN      NaN   
485575                                                NaN  ...  NaN      NaN   
485576                                                NaN  ...  NaN      NaN   

               HMM_Island Regulatory_Feature_Name Regulatory_Feature_Group  \
0                     NaN                     NaN                      NaN   
1       Y:9973136-9976273                     NaN  

In [84]:
new = dmr.copy()

In [85]:
import numpy as np
found = []
for i in features_df_new:
    if not i == "state":

        for x in np.flatnonzero([new['ID'] == i]):
            found.append(x)


In [86]:
import math
mylist = []
for n in found:
    mylist.append(new["UCSC_RefGene_Name"].iloc[n])
print(mylist)

['FLJ12825', nan, 'UBTF;UBTF;UBTF', nan, 'PRPF38B', 'TRAPPC3', 'ODF4', 'ATAD1;CFLP1', nan, 'ANP32B', 'CACNA1S', 'C7orf25;C7orf25', 'SRPK2', 'KRTDAP', 'FBXO2', nan, nan, 'ZNF260;ZNF260;ZNF260;ZNF260', 'PMEPA1;PMEPA1;PMEPA1', 'TOP1MT', nan, 'TBCD', nan, 'MIR380;MIR299', 'RAB13', 'SPATA2L', 'C6orf127', 'CCND1', 'SNHG3-RCC1;SNHG3-RCC1;SNHG3-RCC1;RCC1;RCC1;RCC1', 'ANKRD23', 'RNASEH2B;RNASEH2B', nan, 'DGKD;DGKD', 'SETMAR;SETMAR', 'REG4;REG4', nan, 'RPL23;SNORA21', 'SDCCAG8;AKT3', 'PTPRN2;PTPRN2;PTPRN2', 'BIN1;BIN1;BIN1;BIN1;BIN1;BIN1;BIN1;BIN1;BIN1;BIN1', 'ZEB1;ZEB1;ZEB1;LOC220930;ZEB1', 'TTC32;TTC32', 'NHS', 'TBR1', 'SNORD116-20;SNORD116-17;SNORD116-19', 'EIF2S1;ATP6V1D', 'HCFC1R1;THOC6;HCFC1R1;HCFC1R1;THOC6', 'ZDHHC14;ZDHHC14', 'OPN1SW', 'C20orf108', nan, 'ZNRF1', 'PODNL1;DCAF15;PODNL1', 'MCF2L;MCF2L', nan, nan, 'CCNY;CCNY', 'ZEB2;ZEB2;ZEB2', 'RANBP17', 'CCDC77;CCDC77;CCDC77;CCDC77', 'PPT2;PPT2', 'AKAP13;AKAP13', nan, 'EIF5;EIF5;EIF5', 'NACAD', 'GMDS', 'MLLT10;MLLT10', nan, 'LOC100130015;L

In [87]:
newlist = []
for i in mylist:
    x = str(i)
    newlist.append(x) 
newlist = [x for x in newlist if x != 'nan']
print(newlist)

['FLJ12825', 'UBTF;UBTF;UBTF', 'PRPF38B', 'TRAPPC3', 'ODF4', 'ATAD1;CFLP1', 'ANP32B', 'CACNA1S', 'C7orf25;C7orf25', 'SRPK2', 'KRTDAP', 'FBXO2', 'ZNF260;ZNF260;ZNF260;ZNF260', 'PMEPA1;PMEPA1;PMEPA1', 'TOP1MT', 'TBCD', 'MIR380;MIR299', 'RAB13', 'SPATA2L', 'C6orf127', 'CCND1', 'SNHG3-RCC1;SNHG3-RCC1;SNHG3-RCC1;RCC1;RCC1;RCC1', 'ANKRD23', 'RNASEH2B;RNASEH2B', 'DGKD;DGKD', 'SETMAR;SETMAR', 'REG4;REG4', 'RPL23;SNORA21', 'SDCCAG8;AKT3', 'PTPRN2;PTPRN2;PTPRN2', 'BIN1;BIN1;BIN1;BIN1;BIN1;BIN1;BIN1;BIN1;BIN1;BIN1', 'ZEB1;ZEB1;ZEB1;LOC220930;ZEB1', 'TTC32;TTC32', 'NHS', 'TBR1', 'SNORD116-20;SNORD116-17;SNORD116-19', 'EIF2S1;ATP6V1D', 'HCFC1R1;THOC6;HCFC1R1;HCFC1R1;THOC6', 'ZDHHC14;ZDHHC14', 'OPN1SW', 'C20orf108', 'ZNRF1', 'PODNL1;DCAF15;PODNL1', 'MCF2L;MCF2L', 'CCNY;CCNY', 'ZEB2;ZEB2;ZEB2', 'RANBP17', 'CCDC77;CCDC77;CCDC77;CCDC77', 'PPT2;PPT2', 'AKAP13;AKAP13', 'EIF5;EIF5;EIF5', 'NACAD', 'GMDS', 'MLLT10;MLLT10', 'LOC100130015;LOC100130015', 'CXorf38', 'SNORD34;RPL13AP5;SNORD35A;RPL13A', 'FUT2;FUT

In [88]:
arr3 = []
for i in newlist:
    if ";" in i:
        arr = i.split(";")
        arr2 = set(arr)
        for x in arr2:
            arr3.append(x)
    else:
        arr3.append(x)
print(arr3)

['PTAR1', 'UBTF', 'UBTF', 'UBTF', 'UBTF', 'ATAD1', 'CFLP1', 'CFLP1', 'CFLP1', 'C7orf25', 'C7orf25', 'C7orf25', 'C7orf25', 'ZNF260', 'PMEPA1', 'PMEPA1', 'PMEPA1', 'MIR380', 'MIR299', 'MIR299', 'MIR299', 'MIR299', 'MIR299', 'SNHG3-RCC1', 'RCC1', 'RCC1', 'RNASEH2B', 'DGKD', 'SETMAR', 'REG4', 'RPL23', 'SNORA21', 'SDCCAG8', 'AKT3', 'PTPRN2', 'BIN1', 'LOC220930', 'ZEB1', 'TTC32', 'TTC32', 'TTC32', 'SNORD116-19', 'SNORD116-20', 'SNORD116-17', 'EIF2S1', 'ATP6V1D', 'HCFC1R1', 'THOC6', 'ZDHHC14', 'ZDHHC14', 'ZDHHC14', 'ZDHHC14', 'DCAF15', 'PODNL1', 'MCF2L', 'CCNY', 'ZEB2', 'ZEB2', 'CCDC77', 'PPT2', 'AKAP13', 'EIF5', 'EIF5', 'EIF5', 'MLLT10', 'LOC100130015', 'LOC100130015', 'RPL13A', 'SNORD35A', 'RPL13AP5', 'SNORD34', 'FUT2', 'TLE2', 'TLE2', 'ZCCHC4', 'SEPT9', 'TMEM108', 'TMEM108', 'WDR31', 'WDR31', 'WDR31', 'EIF2S1', 'ATP6V1D', 'ATP6V1D', 'UBXN11', 'UGT1A8', 'UGT1A7', 'UGT1A3', 'UGT1A4', 'UGT1A5', 'UGT1A10', 'UGT1A6', 'UGT1A9', 'PSMB8', 'PSMB8', 'PSMB8', 'PSMB8', 'PSMB8', 'RNF113A', 'NDUFA1', 'B

In [89]:
print(len(arr3))

1788


In [90]:
from collections import Counter
c = Counter(arr3)
c.most_common(5)

[('PTPRN2', 13), ('MINK1', 13), ('IQCE', 12), ('MAD1L1', 11), ('HPGD', 11)]

In [47]:
import pandas as pd
df = pd.DataFrame(arr3, columns=['Genes'])
df.to_csv("FinalGeneListSupercomputing.csv")